### ISSUE TITLE
段階管理機能の追加と教員支援ツールの拡充

### ISSUE THREAD

**Issue by k18rs509** [smkwlab/thesis-management-tools#127]
## 背景
教員主導で学生の学習段階（週報→卒論等）を管理し、段階に応じた適切な支援を提供する機能を追加する。

### 学習段階
- **wr**: 週報執筆（LaTeX基礎学習）
- **thesis-report**: 卒論レポート（LaTeX構造学習）
- **ise**: ISEレポート（PR添削学習）
- **thesis**: 卒業論文（完全版PR添削）

### Phase 1（高優先度）
- [ ] 段階設定スクリプトの作成
  ```bash
  ./scripts/set-student-stage.sh k21rs001 thesis
  ./scripts/bulk-set-stage.sh --stage thesis --students thesis-students.txt
  ```
- [ ] リポジトリ作成時の自動段階登録
  - setup-wr.sh → stage=wr
  - setup.sh → stage=thesis
  - 新規ISE用setup追加検討
- [ ] GitHub Actionsワークフローでの段階情報連携

### Phase 2（中優先度）
- [ ] 段階別テンプレート適用機能
  ```bash
  ./scripts/apply-learning-template.sh --stage wr --students batch.txt
  ./scripts/configure-deadline.sh --stage thesis --date 2025-03-31
  ```
- [ ] 段階別品質チェック
  ```bash
  ./scripts/validate-latex-quality.sh --stage thesis --repository k21rs001-sotsuron
  ./scripts/check-review-compliance.sh --stage thesis --all-active
  ```

### Phase 3（低優先度）
- [ ] 教員支援機能の拡充
  ```bash
  ./scripts/assign-reviewer.sh --student k21rs001 --reviewer prof-tanaka
  ./scripts/bulk-feedback.sh --template constructive-feedback.md
  ./scripts/semester-summary.sh --year 2025 --semester spring
  ```
- [ ] 段階遷移ワークフローの自動化
- [ ] 期限管理とリマインダー機能

### thesis-student-registryとの連携
- 段階情報をrepositories.jsonに記録
- ワークフロー実行時に段階情報を更新
- thesis-monitorでの段階別表示に対応

#### 段階設定スクリプト
```bash
#\!/bin/bash
# scripts/set-student-stage.sh
STUDENT_ID="$1"
STAGE="$2"

# repositories.jsonを更新
# GitHub Actionsでthesis-student-registryに反映
```

#### リポジトリ作成時の段階登録
```yaml
# .github/workflows/student-repo-management.yml に追加
- name: Set student stage
  run: |
    # 作成されたリポジトリタイプに基づいて段階設定
    if [[ "$REPO_NAME" == *"-wr" ]]; then
      STAGE="wr"
    elif [[ "$REPO_NAME" == *"-sotsuron" ]]; then
      STAGE="thesis"
    fi
    
    # thesis-student-registryに段階情報を記録
```

## 期待効果
- 教員が学生の学習段階を明確に管理
- 段階に応じた適切な支援とモニタリング
- 学習進捗の可視化と効率的な指導

関連: thesis-student-registry#3 (段階別モニタリング機能)
